const products = [
  {
    _id: "1",
    name: "Blue Pearl Earrings",
    image: "/images/blue-pearl-earrings.jpg",
    description:
      "Beautiful blue earrings with a pearl and hanging feather like structure",
    brand: "Brand Blue",
    category: "Earrings",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Blue Saphire Ring",
    image: "/images/blue-saphire-ring.jpg",
    description: "Amazing blue saphire ring with diamonds around it",
    brand: "Brand Blue",
    category: "Rings",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Golden Bracelet",
    image: "/images/golden-bracelet.jpg",
    description: "A unique golden bracelet for fancy dinner dates",
    brand: "Brand Gold",
    category: "Bracelets",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Golden Earrings",
    image: "/images/golden-earrings.jpg",
    description: "A set of small but astonishing golden earrings with diamonds",
    brand: "Brand Gold",
    category: "Earrings",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Handmade Wooden Bracelet",
    image: "/images/handmade-bracelet.jpg",
    description:
      "Handmade wooden bracelet made by a master with attention to detail",
    brand: "Brand Wood",
    category: "Bracelets",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Golden Ring",
    image: "/images/golden-ring.jpg",
    description: "A golden ring for your special someone",
    brand: "Brand Gold",
    category: "Rings",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "Jade Necklace",
    image: "/images/jade-necklace.jpg",
    description: "A jade necklace with diamonds, for the most special nights",
    brand: "Brand Jade",
    category: "Necklaces",
    price: 329.99,
    countInStock: 4,
    rating: 5,
    numReviews: 9,
  },
  {
    _id: "8",
    name: "Lion Bracelet",
    image: "/images/lion-bracelet.jpg",
    description: "Lion bracelet for the bravest wearer",
    brand: "Brand Lion",
    category: "Bracelets",
    price: 69.99,
    countInStock: 5,
    rating: 4,
    numReviews: 9,
  },
  {
    _id: "9",
    name: "Diamond Bracelet",
    image: "/images/diamond-bracelet.jpg",
    description:
      "A bracelet made entirely out of diamonds, with a touch of gold",
    brand: "Brand Diamond",
    category: "Bracelets",
    price: 269.99,
    countInStock: 2,
    rating: 5,
    numReviews: 6,
  },
  {
    _id: "10",
    name: "Engagement Ring",
    image: "/images/engagement-ring.jpg",
    description: "An engagement ring, to make your relationship last forever",
    brand: "Brand Diamond",
    category: "Rings",
    price: 349.99,
    countInStock: 2,
    rating: 5,
    numReviews: 9,
  },
  {
    _id: "11",
    name: "Imitation Jewelry",
    image: "/images/imitation-jewelry.jpg",
    description:
      "Bijouterie, for when you just want to look fancy without breaking the bank",
    brand: "Brand Bijouterie",
    category: "Rings",
    price: 9.99,
    countInStock: 8,
    rating: 3,
    numReviews: 5,
  },
  {
    _id: "12",
    name: "Wedding Rings",
    image: "/images/wedding-rings.jpg",
    description: "For your special day",
    brand: "Brand Golden",
    category: "Rings",
    price: 119.99,
    countInStock: 6,
    rating: 5,
    numReviews: 13,
  },
  {
    _id: "13",
    name: "Elegant Bracelet",
    image: "/images/elegant-bracelet.jpg",
    description: "An elegant bracelet, for your caffee lunches with friends",
    brand: "Brand Diamond",
    category: "Bracelets",
    price: 129.99,
    countInStock: 0,
    rating: 5,
    numReviews: 15,
  },
  {
    _id: "14",
    name: "Diamond Earrings",
    image: "/images/diamond-earrings.jpg",
    description: "Diamonds are always a good anniversary gift",
    brand: "Brand Diamond",
    category: "Earrings",
    price: 329.99,
    countInStock: 4,
    rating: 5,
    numReviews: 7,
  },
  {
    _id: "15",
    name: "Flower Necklace",
    image: "/images/flower-necklace.jpg",
    description: "An imitation jewelry necklace for evening walks by the beach",
    brand: "Brand Bijouterie",
    category: "Necklaces",
    price: 29.99,
    countInStock: 5,
    rating: 4,
    numReviews: 5,
  },
];

export default products;
